package protomap

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDefaultProtoAlias(t *testing.T) {
	cases := map[string]string{
		"example.com/svc/gen/grpc/user/v1": "userv1",
		"example.com/svc/gen/grpc/user/v2": "userv2",
		"example.com/svc/gen/grpc/user":    "user",
		"":                                 "",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, defaultProtoAlias(input))
		})
	}
}

func TestDefaultGoAlias(t *testing.T) {
	cases := map[string]string{
		"example.com/svc/internal/database":   "database",
		"example.com/svc/internal/feature/u":  "u",
		"example.com/svc/internal/feature/v3": "featurev3",
		"":                                    "src",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, defaultGoAlias(input))
		})
	}
}

const bunModel = `package database

import (
	"time"

	"github.com/uptrace/bun"
)

type Example struct {
	bun.BaseModel ` + "`bun:\"table:examples,alias:e\"`" + `

	ID          string    ` + "`bun:\"id,pk\"`" + `
	Name        string    ` + "`bun:\"name\"`" + `
	DisplayName *string   ` + "`bun:\"display_name\"`" + `
	Status      string    ` + "`bun:\"status\"`" + `
	CreatedAt   time.Time ` + "`bun:\"created_at\"`" + `

	Owner *Example ` + "`bun:\"rel:belongs-to,join:id=owner_id\"`" + `
}
`

const plainStruct = `package user

type CreateParams struct {
	Email       string
	Username    string
	DisplayName *string
	Status      string
	Profile     *CreateProfileParams
}

type CreateProfileParams struct {
	FirstName *string
	LastName  *string
}
`

// plainStructIDs mirrors a service CreateParams whose foreign keys use Go's ID
// initialism (SkillID), which proto-generated code spells SkillId.
const plainStructIDs = `package objective

type CreateParams struct {
	Name     string
	SkillID  *string
	IsActive bool
}
`

// wrapperStructs mirror the update/patch params that combine a proto message
// with caller-supplied data (an ID, a field mask, a nested CreateParams).
const wrapperStructs = `package objective

type CreateParams struct {
	Name     string
	SkillID  *string
	IsActive bool
}

type UpdateParams struct {
	ID       string
	Name     string
	SkillID  *string
	IsActive bool
}

type PatchParams struct {
	ID        string
	Objective CreateParams
	Fields    []string
}
`

// treeStruct is a self-referential slice relation (a recursive tree), the
// shape that exercises repeated converters.
const treeStruct = `package orgunit

type OrgUnitNode struct {
	Label    string
	Value    string
	Children []OrgUnitNode
}
`

// scalarSliceStruct has repeated-scalar fields, which map 1:1 to proto repeated
// scalar fields without a converter.
const scalarSliceStruct = `package defaults

type SaveDefaults struct {
	RankIDs []int32
	Tags    []string
}
`

func writeFile(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "src.go"), []byte(body), 0o600))
	return dir
}

func bunBaseConfig(dir string) targetConfig {
	return targetConfig{
		GoDir:         dir,
		GoImport:      "example.com/svc/internal/database",
		GoAlias:       "database",
		GoType:        "Example",
		ProtoImport:   "example.com/svc/gen/grpc/example/v1",
		ProtoAlias:    "examplev1",
		ProtoType:     "Example",
		Direction:     dirBoth,
		FuncToProto:   "ExampleToProto",
		FuncFromProto: "ExampleFromProto",
		TargetPointer: true,
		SourcePointer: true,
		Package:       "feature",
		Out:           filepath.Join(dir, "mapper_generated.go"),
		Exclude:       map[string]bool{},
		Converters:    map[string]converterPair{},
	}
}

func TestGenerateBunMode(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)
	require.True(t, isBun)

	src, err := generate(bunBaseConfig(dir), fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Scalars and pointer-scalars are mapped directly (column -> PascalCase).
	assert.Contains(t, out, "Id:          src.ID")
	assert.Contains(t, out, "DisplayName: src.DisplayName")
	assert.Contains(t, out, "ID:          in.Id")

	// time.Time is bridged through timestamppb.
	assert.Contains(t, out, "timestamppb.New(src.CreatedAt)")
	assert.Contains(t, out, "in.CreatedAt.AsTime()")

	// Untouched relations get a TODO marker.
	assert.Contains(t, out, "// TODO: Owner (*Example, relation)")

	// File header + both directions.
	assert.True(t, strings.HasPrefix(out, "// Code generated by mapgen proto; DO NOT EDIT."), out)
	assert.Contains(t, out, "func ExampleToProto(")
	assert.Contains(t, out, "func ExampleFromProto(")
}

func TestGenerateBunModeConvertersAndExclude(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)
	require.True(t, isBun)

	cfg := bunBaseConfig(dir)
	cfg.Converters["Status"] = converterPair{ToProto: "statusToProto", FromProto: "statusFromProto"}
	cfg.Converters["Owner"] = converterPair{ToProto: "ownerToProto", FromProto: "ownerFromProto"}
	cfg.Exclude["DisplayName"] = true

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "statusToProto(src.Status)")
	assert.Contains(t, out, "statusFromProto(in.Status)")
	assert.Contains(t, out, "ownerToProto(src.Owner)")
	assert.Contains(t, out, "ownerFromProto(in.Owner)")
	assert.NotContains(t, out, "DisplayName")
	assert.NotContains(t, out, "// TODO: Owner")
}

func TestGeneratePlainModeReturnsValueType(t *testing.T) {
	dir := writeFile(t, plainStruct)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)
	require.False(t, isBun)

	cfg := targetConfig{
		GoDir:         dir,
		GoImport:      "example.com/svc/internal/feature/user",
		GoAlias:       "user",
		GoType:        "CreateParams",
		ProtoImport:   "example.com/svc/gen/grpc/user/v1",
		ProtoAlias:    "userv1",
		ProtoType:     "CreateUserRequest",
		Unwrap:        "User",
		Direction:     dirFromProto,
		FuncFromProto: "createParamsFromProto",
		TargetPointer: false,
		Package:       "user",
		Out:           filepath.Join(dir, "mapper_generated.go"),
		Exclude:       map[string]bool{},
		Converters: map[string]converterPair{
			"Status":  {FromProto: "userStatusFromProto"},
			"Profile": {FromProto: "createProfileParamsFromProto"},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Value-type return uses zero-value fallback, not nil. Alias matches GoAlias.
	assert.Contains(t, out, "return user.CreateParams{}")
	assert.Contains(t, out, "dst := user.CreateParams{")
	// Direction filter omits the to-proto function entirely.
	assert.NotContains(t, out, "func CreateParamsToProto")
	// Field names match by identity (plain mode), no PascalCase conversion.
	assert.Contains(t, out, "Email:       src.Email")
	// Status / Profile converters are wired up.
	assert.Contains(t, out, "userStatusFromProto(src.Status)")
	assert.Contains(t, out, "createProfileParamsFromProto(src.Profile)")
}

// idCfg builds a from_proto plain-mode target for plainStructIDs, applying the
// given field-name mode and overrides.
func idCfg(dir string, names fieldNameMode, overrides map[string]string) targetConfig {
	return targetConfig{
		GoDir:          dir,
		GoImport:       "example.com/svc/internal/feature/objective",
		GoAlias:        "objective",
		GoType:         "CreateParams",
		GoSelf:         true,
		ProtoImport:    "example.com/svc/gen/grpc/masterdata/v1",
		ProtoAlias:     "mdsv1",
		ProtoType:      "Objective",
		Direction:      dirFromProto,
		FuncFromProto:  "createParamsFromProto",
		TargetPointer:  false,
		Package:        "objective",
		Out:            filepath.Join(dir, "mapper_generated.go"),
		Exclude:        map[string]bool{},
		Converters:     map[string]converterPair{},
		FieldNames:     names,
		FieldOverrides: overrides,
	}
}

func TestPlainModeProtocNamesAlignInitialisms(t *testing.T) {
	dir := writeFile(t, plainStructIDs)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)
	require.False(t, isBun)

	src, err := generate(idCfg(dir, namesProtoc, nil), fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// SkillID reads from proto's SkillId; regular fields are unchanged.
	assert.Contains(t, out, "in.SkillId")
	assert.NotContains(t, out, "in.SkillID")
	assert.Contains(t, out, "in.Name")
	assert.Contains(t, out, "in.IsActive")
}

func TestPlainModeIdentityNamesKeepGoSpelling(t *testing.T) {
	dir := writeFile(t, plainStructIDs)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)

	// Default (identity) mode assumes the proto field matches the Go spelling.
	src, err := generate(idCfg(dir, namesIdentity, nil), fields, isBun)
	require.NoError(t, err)
	assert.Contains(t, string(src), "in.SkillID")
}

func TestFieldOverrideWinsOverFieldNames(t *testing.T) {
	dir := writeFile(t, plainStructIDs)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)

	src, err := generate(idCfg(dir, namesProtoc, map[string]string{"SkillID": "SkillIdentifier"}), fields, isBun)
	require.NoError(t, err)
	out := string(src)
	assert.Contains(t, out, "in.SkillIdentifier")
	assert.NotContains(t, out, "in.SkillId\n")
}

func TestResolveTargetRejectsBadFieldNames(t *testing.T) {
	_, err := resolveTarget(yamlTarget{
		GoDir: "d", GoImport: "i", GoType: "T", ProtoImport: "p", Package: "pkg", Out: "o",
		FieldNames: "weird",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "field_names")
}

func TestExtraArgInjectsIDIntoUpdateParams(t *testing.T) {
	dir := writeFile(t, wrapperStructs)
	fields, isBun, err := parseStruct(dir, "UpdateParams")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/o", GoAlias: "objective", GoType: "UpdateParams",
		GoSelf: true, ProtoImport: "example.com/gen/grpc/m/v1", ProtoAlias: "mdsv1", ProtoType: "Objective",
		Direction: dirFromProto, FuncFromProto: "updateParamsFromProto", TargetPointer: false,
		Package: "objective", Out: filepath.Join(dir, "mapper_generated.go"),
		Exclude: map[string]bool{}, Converters: map[string]converterPair{}, FieldNames: namesProtoc,
		ExtraArgs: []extraArg{{name: "id", typ: "string", field: "ID", expr: "id", before: true}},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "func updateParamsFromProto(id string, in *mdsv1.Objective) UpdateParams")
	assert.Regexp(t, `ID:\s+id,`, out)    // ID comes from the arg, not the proto
	assert.Contains(t, out, "in.SkillId") // other fields still mapped, protoc-normalized
}

func TestExtraArgsAndWholeInputBuildPatchParams(t *testing.T) {
	dir := writeFile(t, wrapperStructs)
	fields, isBun, err := parseStruct(dir, "PatchParams")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/o", GoAlias: "objective", GoType: "PatchParams",
		GoSelf: true, ProtoImport: "example.com/gen/grpc/m/v1", ProtoAlias: "mdsv1", ProtoType: "Objective",
		Direction: dirFromProto, FuncFromProto: "patchParamsFromProto", TargetPointer: false,
		Package: "objective", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{
			"Objective": {FromProto: "createParamsFromProto", WholeInput: true},
		},
		ExtraArgs: []extraArg{
			{name: "id", typ: "string", field: "ID", expr: "id", before: true},
			{name: "mask", typ: "*fieldmaskpb.FieldMask", field: "Fields", expr: "mask.GetPaths()", before: false},
		},
		Imports: []importEntry{{path: "google.golang.org/protobuf/types/known/fieldmaskpb"}},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Extra args bracket the proto input: id before, mask after.
	assert.Contains(t, out, "func patchParamsFromProto(id string, in *mdsv1.Objective, mask *fieldmaskpb.FieldMask) PatchParams")
	assert.Regexp(t, `ID:\s+id,`, out)
	assert.Regexp(t, `Objective:\s+createParamsFromProto\(in\),`, out) // whole-input converter
	assert.Regexp(t, `Fields:\s+mask\.GetPaths\(\),`, out)             // arg expr
	assert.Contains(t, out, `"google.golang.org/protobuf/types/known/fieldmaskpb"`)
}

func TestScalarSliceFromProtoUsesNonNilClone(t *testing.T) {
	dir := writeFile(t, scalarSliceStruct)
	fields, isBun, err := parseStruct(dir, "SaveDefaults")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/d", GoAlias: "defaults", GoType: "SaveDefaults", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/x/v1", ProtoAlias: "xv1", ProtoType: "Defaults",
		Direction: dirFromProto, FuncFromProto: "saveDefaultsFromProto", TargetPointer: false,
		Package: "defaults", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "return SaveDefaults{")
	assert.Contains(t, out, "RankIDs: []int32{}")
	assert.Contains(t, out, "Tags:    []string{}")
	assert.Contains(t, out, "RankIDs: append(make([]int32, 0, len(in.RankIDs)), in.RankIDs...)")
	assert.Contains(t, out, "Tags:    append(make([]string, 0, len(in.Tags)), in.Tags...)")
	assert.NotContains(t, out, "// TODO")
}

func TestWrapOutputScalarSliceUsesNonNilClone(t *testing.T) {
	dir := writeFile(t, scalarSliceStruct)
	fields, isBun, err := parseStruct(dir, "SaveDefaults")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/d", GoAlias: "defaults", GoType: "SaveDefaults", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/x/v1", ProtoAlias: "xv1", ProtoType: "Defaults",
		Direction: dirFromProto, FuncFromProto: "saveDefaultsFromProto", TargetPointer: false,
		Package: "defaults", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{}, WrapOutput: "SaveDefaultsOutput", WrapField: "Body", Getters: true,
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "RankIDs: append(make([]int32, 0, len(in.GetRankIDs())), in.GetRankIDs()...)")
	assert.Contains(t, out, "Tags:    append(make([]string, 0, len(in.GetTags())), in.GetTags()...)")
	assert.NotContains(t, out, "RankIDs: in.GetRankIDs()")
}

func TestWrapOutputWithoutGettersInitializesScalarSlicesBeforeNilGuard(t *testing.T) {
	dir := writeFile(t, scalarSliceStruct)
	fields, isBun, err := parseStruct(dir, "SaveDefaults")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/d", GoAlias: "defaults", GoType: "SaveDefaults", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/x/v1", ProtoAlias: "xv1", ProtoType: "Defaults",
		Direction: dirFromProto, FuncFromProto: "saveDefaultsFromProto", TargetPointer: false,
		Package: "defaults", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{}, WrapOutput: "SaveDefaultsOutput", WrapField: "Body",
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "out.Body = SaveDefaults{\n\t\tRankIDs: []int32{},\n\t\tTags:    []string{},\n\t}")
	assert.Contains(t, out, "if in == nil {\n\t\treturn out\n\t}")
	assert.Contains(t, out, "RankIDs: append(make([]int32, 0, len(in.RankIDs)), in.RankIDs...)")
}

func TestRepeatedToProtoUsesConverterSlicePtr(t *testing.T) {
	dir := writeFile(t, treeStruct)
	fields, isBun, err := parseStruct(dir, "OrgUnitNode")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/o", GoAlias: "orgunit", GoType: "OrgUnitNode", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/common/v1", ProtoAlias: "commonv1", ProtoType: "TreeOption",
		Direction: dirToProto, FuncToProto: "toProtoOrgUnitNode", TargetPointer: true, SourcePointer: true,
		Package: "orgunit", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{
			"Children": {ToProto: "toProtoOrgUnitNode", Repeated: true, ElementPtr: true},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// element_ptr → converter.SlicePtr (mapper takes *elem); empty source stays []
	// rather than nil, matching the hand-written []-init. No append loop.
	assert.Contains(t, out, "dst.Children = converter.SlicePtr(src.Children, toProtoOrgUnitNode)")
	assert.NotContains(t, out, "for i := range src.Children {")
	assert.NotContains(t, out, "// TODO: Children")
	// Scalars still in the literal.
	assert.Contains(t, out, "Label: src.Label")
}

func TestRepeatedToProtoValueUsesConverterSlice(t *testing.T) {
	dir := writeFile(t, treeStruct)
	fields, isBun, err := parseStruct(dir, "OrgUnitNode")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/o", GoAlias: "orgunit", GoType: "OrgUnitNode", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/common/v1", ProtoAlias: "commonv1", ProtoType: "TreeOption",
		Direction: dirToProto, FuncToProto: "toProtoOrgUnitNode", TargetPointer: true, SourcePointer: true,
		Package: "orgunit", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{
			"Children": {ToProto: "toProtoOrgUnitNode", Repeated: true},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "dst.Children = converter.Slice(src.Children, toProtoOrgUnitNode)")
}

func TestSourceValueOmitsPointerAndGuard(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	cfg := bunBaseConfig(dir)
	cfg.Direction = dirToProto
	cfg.SourcePointer = false

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Value source: no pointer in the signature and no nil guard.
	assert.Contains(t, out, "func ExampleToProto(src database.Example) *examplev1.Example {")
	assert.NotContains(t, out, "if src == nil")
	// Fields still map from src directly.
	assert.Contains(t, out, "DisplayName: src.DisplayName")
}

func TestTimeFromProtoHelperReplacesAsTime(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	cfg := bunBaseConfig(dir)
	cfg.Direction = dirFromProto
	cfg.TimeFromProto = "protoutil.TimeFromProto"

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// The helper wraps the raw proto timestamp field; .AsTime() is gone.
	assert.Contains(t, out, "protoutil.TimeFromProto(in.CreatedAt)")
	assert.NotContains(t, out, ".AsTime()")
}

func TestGettersReadValueScalarsViaAccessor(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	cfg := bunBaseConfig(dir)
	cfg.Direction = dirFromProto
	cfg.Getters = true

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Value scalars read through the generated accessor, which derefs a
	// proto3-optional scalar onto the non-pointer Go field.
	assert.Contains(t, out, "in.GetName()")
	assert.Contains(t, out, "in.GetStatus()")
	// Pointer-scalar target keeps direct field access so the pointer survives.
	assert.Contains(t, out, "in.DisplayName")
	assert.NotContains(t, out, "in.GetDisplayName()")
}

func TestGettersRejectedForToProtoOnly(t *testing.T) {
	_, err := resolveTarget(yamlTarget{
		GoDir: "internal/x", GoType: "Example", GoImport: "example.com/x",
		ProtoImport: "example.com/gen/x/v1", ProtoType: "Example",
		Direction: "to_proto", Getters: true,
		Package: "x", Out: "gen/x/mapper_generated.go",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "getters is only valid")
}

const wrapBodyStruct = `package result

type ReviewResult struct {
	ApprovedCount int32
	RejectedCount int32
}
`

func TestWrapOutputEmitsEnvelope(t *testing.T) {
	dir := writeFile(t, wrapBodyStruct)
	fields, isBun, err := parseStruct(dir, "ReviewResult")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/r", GoAlias: "result", GoType: "ReviewResult", GoSelf: true,
		ProtoImport: "example.com/gen/x/v1", ProtoAlias: "xv1", ProtoType: "ReviewResponse",
		Direction: dirFromProto, FuncFromProto: "reviewResultFromProto",
		WrapOutput: "ReviewOutput", WrapField: "Body",
		Package: "result", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Returns the envelope pointer; nil input yields the empty (non-nil) envelope.
	assert.Contains(t, out, "func reviewResultFromProto(in *xv1.ReviewResponse) *ReviewOutput {")
	assert.Contains(t, out, "out := &ReviewOutput{}")
	assert.Contains(t, out, "return out")
	// The mapped body is assigned to the named envelope field.
	assert.Contains(t, out, "out.Body = ReviewResult{")
	assert.Contains(t, out, "in.ApprovedCount")
}

const wrapListBodyStruct = `package result

type Item struct{ Name string }

type ReviewListBody struct {
	Items      []Item
	Pagination Pagination
}

type Pagination struct{ Total int32 }
`

func TestWrapOutputRepeatedUsesConverterAndDropsGuard(t *testing.T) {
	dir := writeFile(t, wrapListBodyStruct)
	fields, isBun, err := parseStruct(dir, "ReviewListBody")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/r", GoAlias: "result", GoType: "ReviewListBody", GoSelf: true,
		ProtoImport: "example.com/gen/x/v1", ProtoAlias: "xv1", ProtoType: "ListResponse",
		Direction: dirFromProto, FuncFromProto: "listFromProto",
		WrapOutput: "ReviewListOutput", WrapField: "Body", Getters: true,
		Package: "result", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{
			"Items":      {FromProto: "itemFromProto", Repeated: true, Deref: true},
			"Pagination": {FromProto: "paginationFromProto"},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// getters → nil-safe reads, so the envelope has no nil guard.
	assert.NotContains(t, out, "if in == nil")
	// repeated+deref → converter.SliceDeref over the getter read.
	assert.Contains(t, out, "converter.SliceDeref(in.GetItems(), itemFromProto)")
	// plain converter reads through the getter too.
	assert.Contains(t, out, "paginationFromProto(in.GetPagination())")
}

func TestWrapOutputRepeatedRequiresGetters(t *testing.T) {
	_, err := resolveTarget(yamlTarget{
		GoDir: "internal/x", GoType: "Body", GoImport: "example.com/x",
		ProtoImport: "example.com/gen/x/v1", ProtoType: "ListResponse",
		Direction: "from_proto", WrapOutput: "Output",
		Converters: map[string]yamlConverter{"Items": {FromProto: "itemFromProto", Repeated: true}},
		Package:    "x", Out: "gen/x/mapper_generated.go",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "requires getters")
}

func TestWrapOutputRejectedForToProto(t *testing.T) {
	_, err := resolveTarget(yamlTarget{
		GoDir: "internal/x", GoType: "ReviewResult", GoImport: "example.com/x",
		ProtoImport: "example.com/gen/x/v1", ProtoType: "ReviewResponse",
		Direction: "both", WrapOutput: "ReviewOutput",
		Package: "x", Out: "gen/x/mapper_generated.go",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "wrap_output requires direction from_proto")
}

func TestTimeFromProtoRejectedForToProtoOnly(t *testing.T) {
	_, err := resolveTarget(yamlTarget{
		GoDir: "internal/x", GoType: "Example", GoImport: "example.com/x",
		ProtoImport: "example.com/gen/x/v1", ProtoType: "Example",
		Direction: "to_proto", TimeFromProto: "protoutil.TimeFromProto",
		Package: "x", Out: "gen/x/mapper_generated.go",
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "time_from_proto is only valid")
}

func TestRepeatedFromProtoUsesConverterSlice(t *testing.T) {
	dir := writeFile(t, treeStruct)
	fields, isBun, err := parseStruct(dir, "OrgUnitNode")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/o", GoAlias: "orgunit", GoType: "OrgUnitNode", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/common/v1", ProtoAlias: "commonv1", ProtoType: "TreeOption",
		Direction: dirFromProto, FuncFromProto: "orgUnitNodeFromProto", TargetPointer: false,
		Package: "orgunit", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{
			"Children": {FromProto: "orgUnitNodeFromProto", Repeated: true},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// converter.Slice keeps an empty/nil source as [] rather than nil, matching
	// the hand-written []-init the frontend relies on; no append loop.
	assert.Contains(t, out, "Children: []OrgUnitNode{}")
	assert.Contains(t, out, "dst.Children = converter.Slice(in.Children, orgUnitNodeFromProto)")
	assert.NotContains(t, out, "for _, e := range in.Children {")
	assert.NotContains(t, out, "// TODO: Children")
}

func TestRepeatedFromProtoDerefUsesSliceDeref(t *testing.T) {
	dir := writeFile(t, treeStruct)
	fields, isBun, err := parseStruct(dir, "OrgUnitNode")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir: dir, GoImport: "example.com/o", GoAlias: "orgunit", GoType: "OrgUnitNode", GoSelf: true,
		ProtoImport: "example.com/gen/grpc/common/v1", ProtoAlias: "commonv1", ProtoType: "TreeOption",
		Direction: dirFromProto, FuncFromProto: "orgUnitNodeFromProto", TargetPointer: false,
		Package: "orgunit", Out: filepath.Join(dir, "mapper_generated.go"), Exclude: map[string]bool{},
		Converters: map[string]converterPair{
			"Children": {FromProto: "orgUnitNodeFromProto", Repeated: true, Deref: true},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "dst.Children = converter.SliceDeref(in.Children, orgUnitNodeFromProto)")
}

func TestWriteEnumToProtoTypedEnum(t *testing.T) {
	var buf bytes.Buffer
	writeEnum(&buf, enumConfig{
		Func: "examCategoryToProto", Direction: dirToProto,
		ProtoAlias: "tsv1", ProtoType: "ExamCategory", GoType: "ExamCategory",
		Default: "EXAM_CATEGORY_UNSPECIFIED",
		Values: []enumValue{
			{goExpr: "ExamCategorySubject", protoVal: "EXAM_CATEGORY_SUBJECT"},
			{goExpr: "ExamCategorySelfAssess", protoVal: "EXAM_CATEGORY_SELF_ASSESS"},
		},
	})
	out := buf.String()

	assert.Contains(t, out, "func examCategoryToProto(v ExamCategory) tsv1.ExamCategory {")
	assert.Contains(t, out, "case ExamCategorySubject:")
	assert.Contains(t, out, "return tsv1.ExamCategory_EXAM_CATEGORY_SUBJECT")
	assert.Contains(t, out, "return tsv1.ExamCategory_EXAM_CATEGORY_UNSPECIFIED") // default
}

func TestWriteEnumFromProtoString(t *testing.T) {
	var buf bytes.Buffer
	writeEnum(&buf, enumConfig{
		Func: "statusFromProto", Direction: dirFromProto,
		ProtoAlias: "tsv1", ProtoType: "MyStatus", GoType: "string",
		Default: "",
		Values:  []enumValue{{goExpr: "DRAFT", protoVal: "MY_STATUS_DRAFT"}},
	})
	out := buf.String()

	// Proto -> string: cases match proto constants, string side is quoted.
	assert.Contains(t, out, "func statusFromProto(v tsv1.MyStatus) string {")
	assert.Contains(t, out, "case tsv1.MyStatus_MY_STATUS_DRAFT:")
	assert.Contains(t, out, `return "DRAFT"`)
	assert.Contains(t, out, "return \"\"") // empty default for string
}

func TestResolveEnumRejectsBothDirection(t *testing.T) {
	_, err := resolveEnum(yamlEnum{
		Func: "f", ProtoImport: "p", ProtoType: "T", GoType: "string", Package: "x", Out: "o",
		Direction: "both", Values: []yamlEnumValue{{Go: "A", Proto: "T_A"}},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "direction")
}

func TestResolveTargetRejectsExtraArgsOutsideFromProto(t *testing.T) {
	_, err := resolveTarget(yamlTarget{
		GoDir: "d", GoImport: "i", GoType: "T", ProtoImport: "p", Package: "pkg", Out: "o",
		Direction: "to_proto",
		ExtraArgs: []yamlExtraArg{{Name: "id", Type: "string", Field: "ID"}},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "extra_args")
}

func TestGenerateSelfPackageOmitsImport(t *testing.T) {
	dir := writeFile(t, plainStruct)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir:         dir,
		GoImport:      "example.com/svc/internal/feature/user",
		GoAlias:       "user",
		GoType:        "CreateParams",
		GoSelf:        true, // out lives in the same package as the source struct
		ProtoImport:   "example.com/svc/gen/grpc/user/v1",
		ProtoAlias:    "userv1",
		ProtoType:     "CreateUserRequest",
		Unwrap:        "User",
		Direction:     dirFromProto,
		FuncFromProto: "createParamsFromProto",
		TargetPointer: false,
		Package:       "user",
		Out:           filepath.Join(dir, "mapper_generated.go"),
		Exclude:       map[string]bool{},
		Converters: map[string]converterPair{
			"Status":  {FromProto: "userStatusFromProto"},
			"Profile": {FromProto: "createProfileParamsFromProto"},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Self-package: no import of the source struct's package, bare type names.
	assert.NotContains(t, out, `"example.com/svc/internal/feature/user"`)
	assert.NotContains(t, out, "user.CreateParams")
	assert.Contains(t, out, "return CreateParams{}")
	assert.Contains(t, out, "dst := CreateParams{")
}

func TestResolveTargetDetectsSelfPackage(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/feature/user
    go_import: example.com/svc/internal/feature/user
    go_type: CreateParams
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_type: CreateUserRequest
    direction: from_proto
    package: user
    out: internal/feature/user/mapper_generated.go
`), 0o600))

	cfg, _, err := loadConfig(configPath)
	require.NoError(t, err)
	assert.True(t, cfg[0].GoSelf, "out dir == go_dir should set GoSelf")
}

func TestRenderGroupMergesMultipleTargets(t *testing.T) {
	bunDir := writeFile(t, bunModel)
	bunFields, bunIsBun, err := parseStruct(bunDir, "Example")
	require.NoError(t, err)

	plainDir := writeFile(t, plainStruct)
	plainFields, plainIsBun, err := parseStruct(plainDir, "CreateParams")
	require.NoError(t, err)

	// Two targets sharing the same Out (1 to_proto from a bun model, 1
	// from_proto from a plain Go struct) should merge into one file with
	// deduplicated imports.
	bunCfg := bunBaseConfig(bunDir)
	bunCfg.Direction = dirToProto
	bunCfg.Out = filepath.Join(t.TempDir(), "merged.go")

	plainCfg := targetConfig{
		GoDir:         plainDir,
		GoImport:      "example.com/svc/internal/feature/user",
		GoAlias:       "user",
		GoType:        "CreateParams",
		ProtoImport:   "example.com/svc/gen/grpc/example/v1", // same proto module as bunCfg
		ProtoAlias:    "examplev1",
		ProtoType:     "Example",
		Direction:     dirFromProto,
		FuncFromProto: "createParamsFromProto",
		TargetPointer: false,
		Package:       "feature",
		Out:           bunCfg.Out, // shared
		Exclude:       map[string]bool{},
		Converters: map[string]converterPair{
			"Status":  {FromProto: "exampleStatusFromProto"},
			"Profile": {FromProto: "createProfileFromProto"},
		},
	}

	members := []genMember{
		{cfg: bunCfg, fields: bunFields, isBun: bunIsBun},
		{cfg: plainCfg, fields: plainFields, isBun: plainIsBun},
	}
	require.NoError(t, validateGroup(members))

	src, err := renderGroup(members)
	require.NoError(t, err)
	out := string(src)

	// One package decl, both functions present in YAML order.
	assert.Equal(t, 1, strings.Count(out, "\npackage feature\n"))
	assert.True(t, strings.Index(out, "func ExampleToProto(") < strings.Index(out, "func createParamsFromProto("),
		"functions should appear in YAML order")

	// Shared proto import appears exactly once.
	assert.Equal(t, 1, strings.Count(out, `examplev1 "example.com/svc/gen/grpc/example/v1"`))

	// Both go-side imports appear (bun: database; plain: user).
	assert.Contains(t, out, `database "example.com/svc/internal/database"`)
	assert.Contains(t, out, `user "example.com/svc/internal/feature/user"`)

	// timestamppb only imported once even if multiple to_proto members need it.
	assert.LessOrEqual(t, strings.Count(out, `"google.golang.org/protobuf/types/known/timestamppb"`), 1)
}

func TestValidateGroupRejectsPackageMismatch(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	a := bunBaseConfig(dir)
	a.Package = "alpha"
	b := bunBaseConfig(dir)
	b.Package = "beta"

	err = validateGroup([]genMember{
		{cfg: a, fields: fields, isBun: isBun},
		{cfg: b, fields: fields, isBun: isBun},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "disagree on package")
}

func TestValidateGroupRejectsAliasConflict(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	a := bunBaseConfig(dir)
	a.ProtoAlias = "examplev1"
	b := bunBaseConfig(dir)
	b.ProtoAlias = "v1ex" // same path, different alias

	err = validateGroup([]genMember{
		{cfg: a, fields: fields, isBun: isBun},
		{cfg: b, fields: fields, isBun: isBun},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "conflicting aliases")
}

func TestGenerateDirectionFilter(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	cfg := bunBaseConfig(dir)
	cfg.Direction = dirToProto

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "func ExampleToProto(")
	assert.NotContains(t, out, "func ExampleFromProto(")
}

func TestParseStructBunVsPlain(t *testing.T) {
	bunDir := writeFile(t, bunModel)
	_, isBun, err := parseStruct(bunDir, "Example")
	require.NoError(t, err)
	assert.True(t, isBun, "struct with bun.BaseModel and bun: tags is bun mode")

	plainDir := writeFile(t, plainStruct)
	_, isBun, err = parseStruct(plainDir, "CreateParams")
	require.NoError(t, err)
	assert.False(t, isBun, "struct without bun tags is plain mode")
}

func TestParseStructMissing(t *testing.T) {
	dir := writeFile(t, "package database\n")
	_, _, err := parseStruct(dir, "Ghost")
	require.Error(t, err)
	assert.Contains(t, err.Error(), `struct "Ghost" not found`)
}

func TestLoadConfigRoundtrip(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    go_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: internal/feature/user/mapper_generated.go
    exclude: [DeletedAt]
    converters:
      Status:
        to_proto: statusToProto
        from_proto: statusFromProto
`), 0o600))

	cfg, _, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 1)

	tgt := cfg[0]
	assert.Equal(t, "internal/database", tgt.GoDir)
	assert.Equal(t, "User", tgt.GoType)
	assert.Equal(t, "User", tgt.ProtoType, "proto_type defaults to go_type")
	assert.Equal(t, "database", tgt.GoAlias, "go_alias derived from import path")
	assert.Equal(t, "userv1", tgt.ProtoAlias, "proto_alias derived from import path")
	assert.Equal(t, dirBoth, tgt.Direction)
	assert.Equal(t, "UserToProto", tgt.FuncToProto, "func_to_proto defaults to <type>ToProto")
	assert.Equal(t, "UserFromProto", tgt.FuncFromProto)
	assert.True(t, tgt.TargetPointer)
	assert.True(t, tgt.Exclude["DeletedAt"])
	assert.Equal(t, "statusToProto", tgt.Converters["Status"].ToProto)
}

func TestLoadConfigModuleAndDefaults(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
module: example.com/svc
defaults:
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_alias: userv1
targets:
    # go_import (module+go_dir), out (go_dir/mapper_generated.go) and the proto
    # import/alias all come from module + defaults.
    - go_dir: internal/feature/user
      go_type: User
      package: user
      direction: to_proto
    # explicit values still win over the derived/default ones.
    - go_dir: internal/feature/user
      go_import: example.com/other/path
      go_type: Account
      proto_import: example.com/svc/gen/grpc/account/v1
      out: internal/custom/out.go
      package: user
      direction: to_proto
`), 0o600))

	cfg, _, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 2)

	derived := cfg[0]
	assert.Equal(t, "example.com/svc/internal/feature/user", derived.GoImport, "go_import = module + / + go_dir")
	assert.Equal(t, "internal/feature/user/mapper_generated.go", derived.Out, "out derived from go_dir")
	assert.Equal(t, "example.com/svc/gen/grpc/user/v1", derived.ProtoImport, "proto_import from defaults")
	assert.Equal(t, "userv1", derived.ProtoAlias, "proto_alias from defaults")

	explicit := cfg[1]
	assert.Equal(t, "example.com/other/path", explicit.GoImport, "explicit go_import wins")
	assert.Equal(t, "internal/custom/out.go", explicit.Out, "explicit out wins")
	assert.Equal(t, "example.com/svc/gen/grpc/account/v1", explicit.ProtoImport, "explicit proto_import wins")
}

func TestConverterImportAutoAdded(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
module: example.com/svc
converter_import: example.com/svc/lib/converter
targets:
    - go_dir: internal/feature/user
      go_type: ListOutputBody
      proto_import: example.com/svc/gen/grpc/user/v1
      proto_type: ListUsersResponse
      direction: from_proto
      func_from_proto: listUsersFromProto
      wrap_output: ListOutput
      getters: true
      package: user
      converters:
          Users: { from_proto: userFromProto, repeated: true }
`), 0o600))

	cfg, _, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 1)
	assert.True(t, cfg[0].usesConverter())
	assert.Equal(t, "example.com/svc/lib/converter", cfg[0].ConverterImport)

	ents := importEntries(genMember{cfg: cfg[0]})
	var found bool
	for _, e := range ents {
		if e.path == "example.com/svc/lib/converter" {
			found = true
		}
	}
	assert.True(t, found, "converter import auto-added for a repeated converter")
}

func TestLoadConfigGroupInheritance(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
module: example.com/svc
groups:
    user:
        go_dir: internal/feature/user
        proto_import: example.com/svc/gen/grpc/user/v1
        proto_alias: userv1
        package: user
        direction: from_proto
        field_names: protoc
        imports:
            - example.com/svc/lib/converter
targets:
    # inherits go_dir/proto/package/direction/field_names from the group
    - { group: user, go_type: User, proto_type: GetUserResponse, func_from_proto: userFromProto }
    # overrides direction; keeps inherited proto/package
    - { group: user, go_type: CreateParams, proto_type: User, direction: to_proto, func_to_proto: createParamsToProto, imports: [example.com/svc/lib/ptr] }
`), 0o600))

	cfg, _, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 2)

	u := cfg[0]
	assert.Equal(t, "internal/feature/user", u.GoDir)
	assert.Equal(t, "example.com/svc/internal/feature/user", u.GoImport, "go_import from module+go_dir")
	assert.Equal(t, "example.com/svc/gen/grpc/user/v1", u.ProtoImport, "proto_import from group")
	assert.Equal(t, "userv1", u.ProtoAlias)
	assert.Equal(t, "user", u.Package)
	assert.Equal(t, dirFromProto, u.Direction)
	require.Len(t, u.Imports, 1)
	assert.Equal(t, "example.com/svc/lib/converter", u.Imports[0].path, "group import inherited")

	c := cfg[1]
	assert.Equal(t, dirToProto, c.Direction, "target overrides group direction")
	assert.Equal(t, "userv1", c.ProtoAlias, "still inherits group proto_alias")
	require.Len(t, c.Imports, 2, "group + target imports merged")
}

func TestLoadConfigEnumGroupInheritance(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
module: example.com/svc
groups:
    user:
        go_dir: internal/feature/user
        proto_import: example.com/svc/gen/grpc/user/v1
        proto_alias: userv1
        package: user
        direction: from_proto
targets:
    - { group: user, go_type: User, proto_type: GetUserResponse, func_from_proto: userFromProto }
enums:
    # inherits go_dir(->out)/proto/package/direction from the group
    - group: user
      func: statusFromProto
      proto_type: UserStatus
      go_type: string
      values:
          - { go: ACTIVE, proto: USER_STATUS_ACTIVE }
    # overrides direction; keeps inherited proto/package/out
    - group: user
      func: statusToProto
      direction: to_proto
      proto_type: UserStatus
      go_type: string
      default: USER_STATUS_UNSPECIFIED
      values:
          - { go: ACTIVE, proto: USER_STATUS_ACTIVE }
`), 0o600))

	_, enums, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, enums, 2)

	from := enums[0]
	assert.Equal(t, "example.com/svc/gen/grpc/user/v1", from.ProtoImport, "proto_import from group")
	assert.Equal(t, "userv1", from.ProtoAlias)
	assert.Equal(t, "user", from.Package)
	assert.Equal(t, "internal/feature/user/mapper_generated.go", from.Out, "out derived from group go_dir")
	assert.Equal(t, dirFromProto, from.Direction)

	to := enums[1]
	assert.Equal(t, dirToProto, to.Direction, "enum overrides group direction")
	assert.Equal(t, "userv1", to.ProtoAlias, "still inherits group proto_alias")
	assert.Equal(t, "internal/feature/user/mapper_generated.go", to.Out)
}

func TestLoadConfigDirectionAndFuncNames(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/feature/user
    go_import: example.com/svc/internal/feature/user
    go_type: CreateParams
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_type: CreateUserRequest
    unwrap: User
    direction: from_proto
    func_from_proto: createParamsFromProto
    target_pointer: false
    package: user
    out: internal/feature/user/mapper_generated.go
`), 0o600))

	cfg, _, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 1)

	tgt := cfg[0]
	assert.Equal(t, "User", tgt.Unwrap)
	assert.Equal(t, dirFromProto, tgt.Direction)
	assert.Equal(t, "createParamsFromProto", tgt.FuncFromProto)
	assert.False(t, tgt.TargetPointer)
}

func TestLoadConfigRejectsUnwrapWithToProtoOnly(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/feature/user
    go_import: example.com/svc/internal/feature/user
    go_type: CreateParams
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_type: CreateUserRequest
    unwrap: User
    direction: to_proto
    package: user
    out: internal/feature/user/mapper_generated.go
`), 0o600))

	_, _, err := loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unwrap is only valid")
}

func TestLoadConfigRejectsMissingFields(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    # go_type missing
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: mapper.go
`), 0o600))

	_, _, err := loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "go_type is required")
}

func TestLoadConfigConverterRequiresMatchingDirection(t *testing.T) {
	dir := t.TempDir()
	// from_proto-only direction: converter needs only from_proto.
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    go_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    direction: from_proto
    package: user
    out: mapper.go
    converters:
      Status:
        from_proto: statusFromProto
`), 0o600))

	_, _, err := loadConfig(configPath)
	require.NoError(t, err, "from_proto-only converter should be accepted when direction is from_proto")

	// direction=both: half-converter rejected.
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    go_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: mapper.go
    converters:
      Status:
        to_proto: statusToProto
`), 0o600))

	_, _, err = loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "needs both to_proto and from_proto")
}
