package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

type field struct {
	path      string
	key       string
	selector  string
	guards    []string
	mapField  string
	validator string
}

type model struct {
	name   string
	fields []modelField
}

type modelField struct {
	name      string
	tag       string
	typeName  string
	isPointer bool
}

type stringList []string

func (l *stringList) String() string {
	return strings.Join(*l, ",")
}

func (l *stringList) Set(value string) error {
	if value == "" {
		return fmt.Errorf("value is required")
	}
	*l = append(*l, value)
	return nil
}

type bucket struct {
	prefix    string
	mapField  string
	validator string
}

type copyRule struct {
	source string
	target string
	guards []string
}

func main() {
	var bucketFlags stringList
	var copyFlags stringList

	filePath := flag.String("file", "", "Go source file containing patch params")
	rootName := flag.String("root", "", "root struct type name")
	outPath := flag.String("out", "", "generated Go output path")
	packageName := flag.String("package", "", "generated Go package name")
	functionName := flag.String("function", "patchFields", "generated function name")
	fieldMapImport := flag.String("fieldmap-import", "", "field map package import path")
	paramType := flag.String("param-type", "PatchParams", "generated function input type")
	dataType := flag.String("data-type", "patchData", "generated function return type")
	rootSelector := flag.String("root-selector", "", "selector for the root patch value, for example params.User")
	pathsSelector := flag.String("paths-selector", "", "selector for patch paths, for example params.Fields")
	flag.Var(&bucketFlags, "bucket", "bucket mapping as path_prefix:data_map_field:validator_func; use root for top-level fields; repeatable")
	flag.Var(&copyFlags, "copy", "optional copy rule as pointer_source:target[:guard,guard]; emits guarded pointer copy; repeatable")
	flag.Parse()

	if *filePath == "" || *rootName == "" || *outPath == "" || *packageName == "" ||
		*fieldMapImport == "" || *rootSelector == "" || *pathsSelector == "" || len(bucketFlags) == 0 {
		panic("file, root, out, package, fieldmap-import, root-selector, paths-selector, and bucket are required")
	}

	models, err := parseModels(*filePath)
	if err != nil {
		panic(err)
	}

	buckets, err := parseBuckets(bucketFlags)
	if err != nil {
		panic(err)
	}

	copyRules, err := parseCopyRules(copyFlags)
	if err != nil {
		panic(err)
	}

	fields := collectFields(models, buckets, *rootName, "", *rootSelector, nil)
	sort.Slice(fields, func(i, j int) bool {
		return fields[i].path < fields[j].path
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by patchfieldgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", *packageName)
	fmt.Fprintf(&buf, "import fieldmap %q\n\n", *fieldMapImport)
	fmt.Fprintf(&buf, "func %s(params %s) %s {\n", *functionName, *paramType, *dataType)
	fmt.Fprintf(&buf, "\tdata := %s{\n", *dataType)
	for _, mapField := range mapFields(buckets) {
		fmt.Fprintf(&buf, "\t\t%s: make(map[string]any),\n", mapField)
	}
	buf.WriteString("\t}\n\n")

	for _, rule := range copyRules {
		conditions := append(append([]string{}, rule.guards...), rule.source)
		fmt.Fprintf(&buf, "\tif %s {\n", nilConditions(conditions))
		fmt.Fprintf(&buf, "\t\t%s = *%s\n", rule.target, rule.source)
		buf.WriteString("\t}\n")
		buf.WriteString("\n")
	}

	fmt.Fprintf(&buf, "\tfor _, path := range %s {\n", *pathsSelector)
	buf.WriteString("\t\tswitch path {\n")
	for _, field := range fields {
		fmt.Fprintf(&buf, "\t\tcase %q:\n", field.path)
		for _, guard := range field.guards {
			fmt.Fprintf(&buf, "\t\t\tif %s == nil {\n", guard)
			fmt.Fprintf(&buf, "\t\t\t\tdata.%s[%q] = nil\n", field.mapField, field.key)
			buf.WriteString("\t\t\t\tcontinue\n")
			buf.WriteString("\t\t\t}\n")
		}
		fmt.Fprintf(&buf, "\t\t\tif %s(%q) {\n", field.validator, field.key)
		fmt.Fprintf(&buf, "\t\t\t\tdata.%s[%q] = %s\n", field.mapField, field.key, field.selector)
		buf.WriteString("\t\t\t}\n")
	}
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\treturn data\n")
	buf.WriteString("}\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*outPath, out, 0o644); err != nil { //nolint:gosec // Generated source should be readable.
		panic(err)
	}
}

func parseModels(path string) (map[string]model, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse model file: %w", err)
	}

	models := make(map[string]model)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		for _, spec := range gen.Specs {
			typeSpec := spec.(*ast.TypeSpec)
			strct, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			models[typeSpec.Name.Name] = parseModel(typeSpec.Name.Name, strct)
		}
	}

	return models, nil
}

func parseModel(name string, strct *ast.StructType) model {
	m := model{name: name}
	for _, field := range strct.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		tag := ""
		if field.Tag != nil {
			tag = reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("field")
		}
		if tag == "" {
			continue
		}

		typeName, isPointer := typeName(field.Type)
		if typeName == "" {
			continue
		}

		m.fields = append(m.fields, modelField{
			name:      field.Names[0].Name,
			tag:       tag,
			typeName:  typeName,
			isPointer: isPointer,
		})
	}
	return m
}

func collectFields(
	models map[string]model,
	buckets []bucket,
	typeName string,
	prefix string,
	selector string,
	guards []string,
) []field {
	m, ok := models[typeName]
	if !ok {
		return nil
	}

	fields := make([]field, 0, len(m.fields))
	for _, modelField := range m.fields {
		path := modelField.tag
		if prefix != "" {
			path = prefix + "." + modelField.tag
		}

		nextSelector := selector + "." + modelField.name
		nextGuards := guards
		if modelField.isPointer {
			nextGuards = append(append([]string{}, guards...), nextSelector)
		}

		if _, ok := models[modelField.typeName]; ok {
			fields = append(fields, collectFields(models, buckets, modelField.typeName, path, nextSelector, nextGuards)...)
			continue
		}

		fieldBucket, ok := bucketFor(buckets, path)
		if !ok {
			continue
		}

		fields = append(fields, field{
			path:      path,
			key:       modelField.tag,
			selector:  nextSelector,
			guards:    guards,
			mapField:  fieldBucket.mapField,
			validator: fieldBucket.validator,
		})
	}
	return fields
}

func typeName(expr ast.Expr) (string, bool) {
	switch expr := expr.(type) {
	case *ast.Ident:
		return expr.Name, false
	case *ast.StarExpr:
		name, _ := typeName(expr.X)
		return name, true
	default:
		return "", false
	}
}

func parseBuckets(flags []string) ([]bucket, error) {
	buckets := make([]bucket, 0, len(flags))
	for _, flag := range flags {
		parts := strings.Split(flag, ":")
		if len(parts) != 3 {
			return nil, fmt.Errorf("invalid bucket %q: expected path_prefix:data_map_field:validator_func", flag)
		}
		prefix := parts[0]
		if prefix == "root" {
			prefix = ""
		}
		buckets = append(buckets, bucket{
			prefix:    prefix,
			mapField:  parts[1],
			validator: parts[2],
		})
	}

	sort.SliceStable(buckets, func(i, j int) bool {
		return len(buckets[i].prefix) > len(buckets[j].prefix)
	})
	return buckets, nil
}

func parseCopyRules(flags []string) ([]copyRule, error) {
	rules := make([]copyRule, 0, len(flags))
	for _, flag := range flags {
		parts := strings.Split(flag, ":")
		if len(parts) < 2 || len(parts) > 3 || parts[0] == "" || parts[1] == "" {
			return nil, fmt.Errorf("invalid copy %q: expected pointer_source:target[:guard,guard]", flag)
		}

		rule := copyRule{source: parts[0], target: parts[1]}
		if len(parts) == 3 && parts[2] != "" {
			rule.guards = strings.Split(parts[2], ",")
		}
		rules = append(rules, rule)
	}
	return rules, nil
}

func bucketFor(buckets []bucket, path string) (bucket, bool) {
	for _, bucket := range buckets {
		if bucket.prefix == "" || path == bucket.prefix || strings.HasPrefix(path, bucket.prefix+".") {
			return bucket, true
		}
	}
	return bucket{}, false
}

func mapFields(buckets []bucket) []string {
	seen := make(map[string]bool, len(buckets))
	fields := make([]string, 0, len(buckets))
	for _, bucket := range buckets {
		if seen[bucket.mapField] {
			continue
		}
		seen[bucket.mapField] = true
		fields = append(fields, bucket.mapField)
	}
	sort.Strings(fields)
	return fields
}

func nilConditions(selectors []string) string {
	conditions := make([]string, len(selectors))
	for i, selector := range selectors {
		conditions[i] = selector + " != nil"
	}
	return strings.Join(conditions, " && ")
}
