package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProtoGoName(t *testing.T) {
	cases := map[string]string{
		"id":           "Id",
		"user_id":      "UserId",
		"display_name": "DisplayName",
		"line1":        "Line1",
		"":             "",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, protoGoName(input))
		})
	}
}

func TestDefaultProtoAlias(t *testing.T) {
	cases := map[string]string{
		"example.com/svc/gen/grpc/user/v1": "userv1",
		"example.com/svc/gen/grpc/user/v2": "userv2",
		"example.com/svc/gen/grpc/user":    "user",
		"":                                 "",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, defaultProtoAlias(input))
		})
	}
}

const exampleModel = `package database

import (
	"time"

	"github.com/uptrace/bun"
)

type Example struct {
	bun.BaseModel ` + "`bun:\"table:examples,alias:e\"`" + `

	ID          string    ` + "`bun:\"id,pk\"`" + `
	Name        string    ` + "`bun:\"name\"`" + `
	DisplayName *string   ` + "`bun:\"display_name\"`" + `
	Status      string    ` + "`bun:\"status\"`" + `
	CreatedAt   time.Time ` + "`bun:\"created_at\"`" + `

	Owner *Example ` + "`bun:\"rel:belongs-to,join:id=owner_id\"`" + `
}
`

func writeExampleModel(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "model.go"), []byte(exampleModel), 0o600))
	return dir
}

func baseConfig(dir string) targetConfig {
	return targetConfig{
		BunDir:      dir,
		BunImport:   "example.com/svc/internal/database",
		BunAlias:    "database",
		BunType:     "Example",
		ProtoImport: "example.com/svc/gen/grpc/example/v1",
		ProtoAlias:  "examplev1",
		ProtoType:   "Example",
		Package:     "feature",
		Out:         filepath.Join(dir, "mapper_generated.go"),
		Exclude:     map[string]bool{},
		Converters:  map[string]converterPair{},
	}
}

func TestGenerateScalarTimeAndUnmappable(t *testing.T) {
	dir := writeExampleModel(t)
	fields, err := parseModel(dir, "Example")
	require.NoError(t, err)

	src, err := generate(baseConfig(dir), fields)
	require.NoError(t, err)
	out := string(src)

	// Scalars and pointer-scalars are mapped directly.
	assert.Contains(t, out, "Id:          src.ID")
	assert.Contains(t, out, "Name:        src.Name")
	assert.Contains(t, out, "DisplayName: src.DisplayName")
	assert.Contains(t, out, "ID:          src.Id")

	// time.Time is bridged through timestamppb.
	assert.Contains(t, out, "timestamppb.New(src.CreatedAt)")
	assert.Contains(t, out, "src.CreatedAt.AsTime()")
	assert.Contains(t, out, `"google.golang.org/protobuf/types/known/timestamppb"`)

	// Untouched relations get a TODO marker.
	assert.Contains(t, out, "// TODO: Owner (*Example, relation)")

	// File header + both directions.
	assert.True(t, strings.HasPrefix(out, "// Code generated by bunprotogen; DO NOT EDIT."), out)
	assert.Contains(t, out, "func ExampleToProto(")
	assert.Contains(t, out, "func ExampleFromProto(")
}

func TestGenerateWithConverters(t *testing.T) {
	dir := writeExampleModel(t)
	fields, err := parseModel(dir, "Example")
	require.NoError(t, err)

	cfg := baseConfig(dir)
	cfg.Converters = map[string]converterPair{
		"Status": {ToProto: "exampleStatusToProto", FromProto: "exampleStatusFromProto"},
		"Owner":  {ToProto: "exampleOwnerToProto", FromProto: "exampleOwnerFromProto"},
	}

	src, err := generate(cfg, fields)
	require.NoError(t, err)
	out := string(src)

	// Converters take precedence over the scalar default for Status.
	assert.Contains(t, out, "exampleStatusToProto(src.Status)")
	assert.Contains(t, out, "exampleStatusFromProto(src.Status)")

	// Converters cover relations that would otherwise be TODOs.
	assert.Contains(t, out, "exampleOwnerToProto(src.Owner)")
	assert.Contains(t, out, "exampleOwnerFromProto(src.Owner)")
	assert.NotContains(t, out, "// TODO: Owner")
}

func TestGenerateRespectsExclude(t *testing.T) {
	dir := writeExampleModel(t)
	fields, err := parseModel(dir, "Example")
	require.NoError(t, err)

	cfg := baseConfig(dir)
	cfg.Exclude = map[string]bool{"DisplayName": true, "CreatedAt": true}

	src, err := generate(cfg, fields)
	require.NoError(t, err)
	out := string(src)

	assert.NotContains(t, out, "DisplayName")
	assert.NotContains(t, out, "CreatedAt")
	// Excluding the only time.Time field also drops the timestamppb import.
	assert.NotContains(t, out, "timestamppb")
}

func TestLoadConfigRoundtrip(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "bunprotogen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - bun_dir: internal/database
    bun_import: example.com/svc/internal/database
    bun_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: internal/feature/user/mapper_generated.go
    exclude: [DeletedAt]
    converters:
      Status:
        to_proto: statusToProto
        from_proto: statusFromProto
`), 0o600))

	cfg, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 1)

	tgt := cfg[0]
	assert.Equal(t, "internal/database", tgt.BunDir)
	assert.Equal(t, "User", tgt.BunType)
	assert.Equal(t, "User", tgt.ProtoType, "proto_type defaults to bun_type")
	assert.Equal(t, "database", tgt.BunAlias, "bun_alias defaults to database")
	assert.Equal(t, "userv1", tgt.ProtoAlias, "proto_alias derived from import path")
	assert.True(t, tgt.Exclude["DeletedAt"])
	assert.Equal(t, "statusToProto", tgt.Converters["Status"].ToProto)
	assert.Equal(t, "statusFromProto", tgt.Converters["Status"].FromProto)
}

func TestLoadConfigRejectsMissingFields(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "bunprotogen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - bun_dir: internal/database
    bun_import: example.com/svc/internal/database
    # bun_type missing
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: mapper.go
`), 0o600))

	_, err := loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "bun_type is required")
}

func TestLoadConfigRejectsHalfConverter(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "bunprotogen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - bun_dir: internal/database
    bun_import: example.com/svc/internal/database
    bun_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: mapper.go
    converters:
      Status:
        to_proto: statusToProto
        # from_proto missing
`), 0o600))

	_, err := loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "converter for \"Status\" needs both")
}

func TestParseModelMissing(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "model.go"), []byte("package database\n"), 0o600))

	_, err := parseModel(dir, "Ghost")
	require.Error(t, err)
	assert.Contains(t, err.Error(), `model type "Ghost" not found`)
}
