// Package fieldmap implements the "mapgen fields" subcommand: it scans a
// directory of Bun ORM model files and emits, for each requested root model,
// the field-to-column maps consumed at runtime by lib-orm's query and patch
// helpers.
//
// For a root type `User`, the generated file declares:
//
//   - <Root>RootFields — map[string]string of top-level field → column.
//   - <RelatedModel>Fields — one such map for every has-one/has-many child
//     relation reachable from the root.
//   - <Root>Columns — the aggregated map of dotted path → qualified column,
//     used by orm.ApplyFilters and orm.ApplyOrderBy.
//
// Earlier releases also emitted per-model `IsXxxField(field string) bool`
// helpers and a `<Root>RootNestedName` const. Both were used only by an
// internal call inside mapgen patch-generated dispatchers, which no longer
// performs that lookup. Bumping the generator drops those declarations from
// the regenerated output.
package fieldmap

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kitti12911/lib-orm/v4/internal/codegen"
)

const rootNestedName = "root"

type model struct {
	name      string
	table     string
	alias     string
	columns   map[string]string
	relations []relation
}

type relation struct {
	name  string
	model string
	// walk is true when the related model's columns should be folded into the
	// root's column map (any bun relation type: has-one, has-many, belongs-to,
	// many-to-many). Joined columns are qualified by the relation-path alias.
	walk bool
	// forward is true for has-one/has-many/many-to-many (owning) relations and
	// false for belongs-to (back-reference). Root discovery treats a model as a
	// child only when another model forward-relates to it.
	forward bool
}

const (
	modelDirRel = "internal/database"
	outPathRel  = "gen/database/fieldmap_generated.go"
	packageName = "database"
)

// Run generates bun field/column maps with zero configuration. Roots are
// discovered automatically (any model not targeted by a forward relation);
// paths follow the standard layout. -C sets the repo root (default ".").
func Run(args []string) error {
	fs := flag.NewFlagSet("mapgen fields", flag.ContinueOnError)
	dir := fs.String("C", ".", "repo root directory")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	modelDir := filepath.Join(*dir, modelDirRel)
	outPath := filepath.Join(*dir, outPathRel)

	models, err := parseModelDir(modelDir)
	if err != nil {
		return err
	}

	roots := discoverRoots(models)
	if len(roots) == 0 {
		return errors.New("no root models found")
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by mapgen fields; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", packageName)

	for _, rootName := range roots {
		root := models[rootName]

		fieldMaps := map[string]fieldMap{}
		visit(models, root, rootNestedName, fieldMaps, map[string]bool{})

		// Per-model field maps. The root model becomes `<Root>RootFields`;
		// child relations contribute `<RelatedModel>Fields`. Both feed
		// orm.WritableColumns and friends.
		writeMap(&buf, root.name+"RootFields", fieldMaps[rootNestedName].fields)

		nestedNames := make([]string, 0, len(fieldMaps))
		for nestedName := range fieldMaps {
			if nestedName == rootNestedName {
				continue
			}
			nestedNames = append(nestedNames, nestedName)
		}
		sort.Strings(nestedNames)

		for _, nestedName := range nestedNames {
			nestedFieldMap := fieldMaps[nestedName]
			writeMap(&buf, nestedFieldMap.modelName+"Fields", nestedFieldMap.fields)
		}

		// Aggregate map of dotted-path → qualified column, consumed by
		// orm.ApplyFilters and orm.ApplyOrderBy.
		writeMap(&buf, root.name+"Columns", columnsFor(fieldMaps))
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := codegen.WriteFileAtomic(outPath, out); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}

// discoverRoots returns the model names that no other model forward-relates to
// (has-one/has-many/many-to-many), sorted. Belongs-to back-references are
// ignored so a child pointing back at its parent does not demote the parent.
func discoverRoots(models map[string]model) []string {
	child := make(map[string]bool)
	for _, m := range models {
		for _, rel := range m.relations {
			if rel.forward {
				child[rel.model] = true
			}
		}
	}

	roots := make([]string, 0)
	for name := range models {
		if !child[name] {
			roots = append(roots, name)
		}
	}
	sort.Strings(roots)
	return roots
}

type fieldMap struct {
	modelName string
	fields    map[string]string
	alias     string
}

func visit(models map[string]model, m model, nestedName string, fieldMaps map[string]fieldMap, seen map[string]bool) {
	if seen[m.name] {
		return
	}
	seen[m.name] = true

	fieldMaps[nestedName] = fieldMap{
		modelName: m.name,
		fields:    m.columns,
		alias:     queryAlias(m, nestedName),
	}

	for _, rel := range m.relations {
		if !rel.walk {
			continue
		}

		relModel, ok := models[rel.model]
		if !ok {
			continue
		}

		childName := codegen.Snake(rel.name)
		if nestedName != rootNestedName {
			childName = nestedName + "." + childName
		}
		visit(models, relModel, childName, fieldMaps, seen)
	}
}

func parseModelDir(dir string) (map[string]model, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read model directory: %w", err)
	}

	models := make(map[string]model)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		fileModels, err := parseModelFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		maps.Copy(models, fileModels)
	}

	return models, nil
}

func parseModelFile(path string) (map[string]model, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse model file: %w", err)
	}

	models := make(map[string]model)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		for _, spec := range gen.Specs {
			typeSpec := spec.(*ast.TypeSpec)
			strct, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			m, ok := parseModel(typeSpec.Name.Name, strct)
			if ok {
				models[m.name] = m
			}
		}
	}

	return models, nil
}

func parseModel(name string, strct *ast.StructType) (model, bool) {
	m := model{
		name:    name,
		columns: make(map[string]string),
	}

	for _, field := range strct.Fields.List {
		tag := codegen.StructTag(field)
		bunTag := tag.Get("bun")
		if bunTag == "" {
			continue
		}

		if len(field.Names) == 0 && strings.Contains(bunTag, "table:") {
			m.table = tagOptionValue(bunTag, "table")
			m.alias = tagOptionValue(bunTag, "alias")
			continue
		}

		if len(field.Names) == 0 {
			continue
		}

		fieldName := field.Names[0].Name
		if strings.Contains(bunTag, "rel:") {
			m.relations = append(m.relations, relation{
				name:    fieldName,
				model:   modelTypeName(field.Type),
				walk:    isWalkableRelation(bunTag),
				forward: isForwardRelation(bunTag),
			})
			continue
		}

		column := strings.Split(bunTag, ",")[0]
		if column == "" {
			continue
		}
		m.columns[codegen.Snake(fieldName)] = column
	}

	sort.Slice(m.relations, func(i, j int) bool {
		return m.relations[i].name < m.relations[j].name
	})

	return m, m.table != ""
}

func columnsFor(fieldMaps map[string]fieldMap) map[string]string {
	columns := make(map[string]string)
	for nestedName, fieldMap := range fieldMaps {
		for field, column := range fieldMap.fields {
			key := field
			if nestedName != rootNestedName {
				key = nestedName + "." + field
			}
			columns[key] = qualifyColumn(fieldMap.alias, column)
		}
	}
	return columns
}

func qualifyColumn(alias, column string) string {
	if alias == "" {
		return column
	}
	return alias + "." + column
}

func queryAlias(m model, nestedName string) string {
	if nestedName == rootNestedName {
		return m.alias
	}
	return strings.ReplaceAll(nestedName, ".", "__")
}

func tagOptionValue(tag, key string) string {
	for opt := range strings.SplitSeq(tag, ",") {
		if value, ok := strings.CutPrefix(opt, key+":"); ok {
			return value
		}
	}
	return ""
}

// isWalkableRelation reports whether a bun relation tag is one whose related
// model contributes columns to the root's filter/order map. All four bun
// relation kinds qualify: bun joins each under a relation-path alias, so a
// filter like "skill.name" resolves regardless of relation direction.
func isWalkableRelation(tag string) bool {
	for opt := range strings.SplitSeq(tag, ",") {
		switch opt {
		case "rel:has-one", "rel:has-many", "rel:belongs-to", "rel:many-to-many":
			return true
		}
	}
	return false
}

// isForwardRelation reports whether a bun relation tag is an owning relation
// (has-one/has-many/many-to-many) as opposed to a belongs-to back-reference.
// The target of a forward relation is a child, never a root.
func isForwardRelation(tag string) bool {
	for opt := range strings.SplitSeq(tag, ",") {
		switch opt {
		case "rel:has-one", "rel:has-many", "rel:many-to-many":
			return true
		}
	}
	return false
}

func modelTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		return modelTypeName(t.X)
	case *ast.ArrayType:
		return modelTypeName(t.Elt)
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

func writeMap(buf *bytes.Buffer, name string, fields map[string]string) {
	fmt.Fprintf(buf, "var %s = map[string]string{\n", name)
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", key, fields[key])
	}
	buf.WriteString("}\n\n")
}
