package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProtoGoName(t *testing.T) {
	cases := map[string]string{
		"id":           "Id",
		"user_id":      "UserId",
		"display_name": "DisplayName",
		"line1":        "Line1",
		"":             "",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, protoGoName(input))
		})
	}
}

func TestDefaultProtoAlias(t *testing.T) {
	cases := map[string]string{
		"example.com/svc/gen/grpc/user/v1": "userv1",
		"example.com/svc/gen/grpc/user/v2": "userv2",
		"example.com/svc/gen/grpc/user":    "user",
		"":                                 "",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, defaultProtoAlias(input))
		})
	}
}

func TestDefaultGoAlias(t *testing.T) {
	cases := map[string]string{
		"example.com/svc/internal/database":   "database",
		"example.com/svc/internal/feature/u":  "u",
		"example.com/svc/internal/feature/v3": "featurev3",
		"":                                    "src",
	}
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, want, defaultGoAlias(input))
		})
	}
}

const bunModel = `package database

import (
	"time"

	"github.com/uptrace/bun"
)

type Example struct {
	bun.BaseModel ` + "`bun:\"table:examples,alias:e\"`" + `

	ID          string    ` + "`bun:\"id,pk\"`" + `
	Name        string    ` + "`bun:\"name\"`" + `
	DisplayName *string   ` + "`bun:\"display_name\"`" + `
	Status      string    ` + "`bun:\"status\"`" + `
	CreatedAt   time.Time ` + "`bun:\"created_at\"`" + `

	Owner *Example ` + "`bun:\"rel:belongs-to,join:id=owner_id\"`" + `
}
`

const plainStruct = `package user

type CreateParams struct {
	Email       string
	Username    string
	DisplayName *string
	Status      string
	Profile     *CreateProfileParams
}

type CreateProfileParams struct {
	FirstName *string
	LastName  *string
}
`

func writeFile(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "src.go"), []byte(body), 0o600))
	return dir
}

func bunBaseConfig(dir string) targetConfig {
	return targetConfig{
		GoDir:         dir,
		GoImport:      "example.com/svc/internal/database",
		GoAlias:       "database",
		GoType:        "Example",
		ProtoImport:   "example.com/svc/gen/grpc/example/v1",
		ProtoAlias:    "examplev1",
		ProtoType:     "Example",
		Direction:     dirBoth,
		FuncToProto:   "ExampleToProto",
		FuncFromProto: "ExampleFromProto",
		TargetPointer: true,
		Package:       "feature",
		Out:           filepath.Join(dir, "mapper_generated.go"),
		Exclude:       map[string]bool{},
		Converters:    map[string]converterPair{},
	}
}

func TestGenerateBunMode(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)
	require.True(t, isBun)

	src, err := generate(bunBaseConfig(dir), fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Scalars and pointer-scalars are mapped directly (column → PascalCase).
	assert.Contains(t, out, "Id:          src.ID")
	assert.Contains(t, out, "DisplayName: src.DisplayName")
	assert.Contains(t, out, "ID:          in.Id")

	// time.Time is bridged through timestamppb.
	assert.Contains(t, out, "timestamppb.New(src.CreatedAt)")
	assert.Contains(t, out, "in.CreatedAt.AsTime()")

	// Untouched relations get a TODO marker.
	assert.Contains(t, out, "// TODO: Owner (*Example, relation)")

	// File header + both directions.
	assert.True(t, strings.HasPrefix(out, "// Code generated by protomapgen; DO NOT EDIT."), out)
	assert.Contains(t, out, "func ExampleToProto(")
	assert.Contains(t, out, "func ExampleFromProto(")
}

func TestGenerateBunModeConvertersAndExclude(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)
	require.True(t, isBun)

	cfg := bunBaseConfig(dir)
	cfg.Converters["Status"] = converterPair{ToProto: "statusToProto", FromProto: "statusFromProto"}
	cfg.Converters["Owner"] = converterPair{ToProto: "ownerToProto", FromProto: "ownerFromProto"}
	cfg.Exclude["DisplayName"] = true

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "statusToProto(src.Status)")
	assert.Contains(t, out, "statusFromProto(in.Status)")
	assert.Contains(t, out, "ownerToProto(src.Owner)")
	assert.Contains(t, out, "ownerFromProto(in.Owner)")
	assert.NotContains(t, out, "DisplayName")
	assert.NotContains(t, out, "// TODO: Owner")
}

func TestGeneratePlainModeReturnsValueType(t *testing.T) {
	dir := writeFile(t, plainStruct)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)
	require.False(t, isBun)

	cfg := targetConfig{
		GoDir:         dir,
		GoImport:      "example.com/svc/internal/feature/user",
		GoAlias:       "user",
		GoType:        "CreateParams",
		ProtoImport:   "example.com/svc/gen/grpc/user/v1",
		ProtoAlias:    "userv1",
		ProtoType:     "CreateUserRequest",
		Unwrap:        "User",
		Direction:     dirFromProto,
		FuncFromProto: "createParamsFromProto",
		TargetPointer: false,
		Package:       "user",
		Out:           filepath.Join(dir, "mapper_generated.go"),
		Exclude:       map[string]bool{},
		Converters: map[string]converterPair{
			"Status":  {FromProto: "userStatusFromProto"},
			"Profile": {FromProto: "createProfileParamsFromProto"},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Value-type return uses zero-value fallback, not nil. Alias matches GoAlias.
	assert.Contains(t, out, "return user.CreateParams{}")
	assert.Contains(t, out, "dst := user.CreateParams{")
	// Direction filter omits the to-proto function entirely.
	assert.NotContains(t, out, "func CreateParamsToProto")
	// Field names match by identity (plain mode), no PascalCase conversion.
	assert.Contains(t, out, "Email:       src.Email")
	// Status / Profile converters are wired up.
	assert.Contains(t, out, "userStatusFromProto(src.Status)")
	assert.Contains(t, out, "createProfileParamsFromProto(src.Profile)")
}

func TestGenerateSelfPackageOmitsImport(t *testing.T) {
	dir := writeFile(t, plainStruct)
	fields, isBun, err := parseStruct(dir, "CreateParams")
	require.NoError(t, err)

	cfg := targetConfig{
		GoDir:         dir,
		GoImport:      "example.com/svc/internal/feature/user",
		GoAlias:       "user",
		GoType:        "CreateParams",
		GoSelf:        true, // out lives in the same package as the source struct
		ProtoImport:   "example.com/svc/gen/grpc/user/v1",
		ProtoAlias:    "userv1",
		ProtoType:     "CreateUserRequest",
		Unwrap:        "User",
		Direction:     dirFromProto,
		FuncFromProto: "createParamsFromProto",
		TargetPointer: false,
		Package:       "user",
		Out:           filepath.Join(dir, "mapper_generated.go"),
		Exclude:       map[string]bool{},
		Converters: map[string]converterPair{
			"Status":  {FromProto: "userStatusFromProto"},
			"Profile": {FromProto: "createProfileParamsFromProto"},
		},
	}

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	// Self-package: no import of the source struct's package, bare type names.
	assert.NotContains(t, out, `"example.com/svc/internal/feature/user"`)
	assert.NotContains(t, out, "user.CreateParams")
	assert.Contains(t, out, "return CreateParams{}")
	assert.Contains(t, out, "dst := CreateParams{")
}

func TestResolveTargetDetectsSelfPackage(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/feature/user
    go_import: example.com/svc/internal/feature/user
    go_type: CreateParams
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_type: CreateUserRequest
    direction: from_proto
    package: user
    out: internal/feature/user/mapper_generated.go
`), 0o600))

	cfg, err := loadConfig(configPath)
	require.NoError(t, err)
	assert.True(t, cfg[0].GoSelf, "out dir == go_dir should set GoSelf")
}

func TestRenderGroupMergesMultipleTargets(t *testing.T) {
	bunDir := writeFile(t, bunModel)
	bunFields, bunIsBun, err := parseStruct(bunDir, "Example")
	require.NoError(t, err)

	plainDir := writeFile(t, plainStruct)
	plainFields, plainIsBun, err := parseStruct(plainDir, "CreateParams")
	require.NoError(t, err)

	// Two targets sharing the same Out (1 to_proto from a bun model, 1
	// from_proto from a plain Go struct) should merge into one file with
	// deduplicated imports.
	bunCfg := bunBaseConfig(bunDir)
	bunCfg.Direction = dirToProto
	bunCfg.Out = filepath.Join(t.TempDir(), "merged.go")

	plainCfg := targetConfig{
		GoDir:         plainDir,
		GoImport:      "example.com/svc/internal/feature/user",
		GoAlias:       "user",
		GoType:        "CreateParams",
		ProtoImport:   "example.com/svc/gen/grpc/example/v1", // same proto module as bunCfg
		ProtoAlias:    "examplev1",
		ProtoType:     "Example",
		Direction:     dirFromProto,
		FuncFromProto: "createParamsFromProto",
		TargetPointer: false,
		Package:       "feature",
		Out:           bunCfg.Out, // shared
		Exclude:       map[string]bool{},
		Converters: map[string]converterPair{
			"Status":  {FromProto: "exampleStatusFromProto"},
			"Profile": {FromProto: "createProfileFromProto"},
		},
	}

	members := []genMember{
		{cfg: bunCfg, fields: bunFields, isBun: bunIsBun},
		{cfg: plainCfg, fields: plainFields, isBun: plainIsBun},
	}
	require.NoError(t, validateGroup(members))

	src, err := renderGroup(members)
	require.NoError(t, err)
	out := string(src)

	// One package decl, both functions present in YAML order.
	assert.Equal(t, 1, strings.Count(out, "\npackage feature\n"))
	assert.True(t, strings.Index(out, "func ExampleToProto(") < strings.Index(out, "func createParamsFromProto("),
		"functions should appear in YAML order")

	// Shared proto import appears exactly once.
	assert.Equal(t, 1, strings.Count(out, `examplev1 "example.com/svc/gen/grpc/example/v1"`))

	// Both go-side imports appear (bun: database; plain: user).
	assert.Contains(t, out, `database "example.com/svc/internal/database"`)
	assert.Contains(t, out, `user "example.com/svc/internal/feature/user"`)

	// timestamppb only imported once even if multiple to_proto members need it.
	assert.LessOrEqual(t, strings.Count(out, `"google.golang.org/protobuf/types/known/timestamppb"`), 1)
}

func TestValidateGroupRejectsPackageMismatch(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	a := bunBaseConfig(dir)
	a.Package = "alpha"
	b := bunBaseConfig(dir)
	b.Package = "beta"

	err = validateGroup([]genMember{
		{cfg: a, fields: fields, isBun: isBun},
		{cfg: b, fields: fields, isBun: isBun},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "disagree on package")
}

func TestValidateGroupRejectsAliasConflict(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	a := bunBaseConfig(dir)
	a.ProtoAlias = "examplev1"
	b := bunBaseConfig(dir)
	b.ProtoAlias = "v1ex" // same path, different alias

	err = validateGroup([]genMember{
		{cfg: a, fields: fields, isBun: isBun},
		{cfg: b, fields: fields, isBun: isBun},
	})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "conflicting aliases")
}

func TestGenerateDirectionFilter(t *testing.T) {
	dir := writeFile(t, bunModel)
	fields, isBun, err := parseStruct(dir, "Example")
	require.NoError(t, err)

	cfg := bunBaseConfig(dir)
	cfg.Direction = dirToProto

	src, err := generate(cfg, fields, isBun)
	require.NoError(t, err)
	out := string(src)

	assert.Contains(t, out, "func ExampleToProto(")
	assert.NotContains(t, out, "func ExampleFromProto(")
}

func TestParseStructBunVsPlain(t *testing.T) {
	bunDir := writeFile(t, bunModel)
	_, isBun, err := parseStruct(bunDir, "Example")
	require.NoError(t, err)
	assert.True(t, isBun, "struct with bun.BaseModel and bun: tags is bun mode")

	plainDir := writeFile(t, plainStruct)
	_, isBun, err = parseStruct(plainDir, "CreateParams")
	require.NoError(t, err)
	assert.False(t, isBun, "struct without bun tags is plain mode")
}

func TestParseStructMissing(t *testing.T) {
	dir := writeFile(t, "package database\n")
	_, _, err := parseStruct(dir, "Ghost")
	require.Error(t, err)
	assert.Contains(t, err.Error(), `struct "Ghost" not found`)
}

func TestLoadConfigRoundtrip(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    go_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: internal/feature/user/mapper_generated.go
    exclude: [DeletedAt]
    converters:
      Status:
        to_proto: statusToProto
        from_proto: statusFromProto
`), 0o600))

	cfg, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 1)

	tgt := cfg[0]
	assert.Equal(t, "internal/database", tgt.GoDir)
	assert.Equal(t, "User", tgt.GoType)
	assert.Equal(t, "User", tgt.ProtoType, "proto_type defaults to go_type")
	assert.Equal(t, "database", tgt.GoAlias, "go_alias derived from import path")
	assert.Equal(t, "userv1", tgt.ProtoAlias, "proto_alias derived from import path")
	assert.Equal(t, dirBoth, tgt.Direction)
	assert.Equal(t, "UserToProto", tgt.FuncToProto, "func_to_proto defaults to <type>ToProto")
	assert.Equal(t, "UserFromProto", tgt.FuncFromProto)
	assert.True(t, tgt.TargetPointer)
	assert.True(t, tgt.Exclude["DeletedAt"])
	assert.Equal(t, "statusToProto", tgt.Converters["Status"].ToProto)
}

func TestLoadConfigDirectionAndFuncNames(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/feature/user
    go_import: example.com/svc/internal/feature/user
    go_type: CreateParams
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_type: CreateUserRequest
    unwrap: User
    direction: from_proto
    func_from_proto: createParamsFromProto
    target_pointer: false
    package: user
    out: internal/feature/user/mapper_generated.go
`), 0o600))

	cfg, err := loadConfig(configPath)
	require.NoError(t, err)
	require.Len(t, cfg, 1)

	tgt := cfg[0]
	assert.Equal(t, "User", tgt.Unwrap)
	assert.Equal(t, dirFromProto, tgt.Direction)
	assert.Equal(t, "createParamsFromProto", tgt.FuncFromProto)
	assert.False(t, tgt.TargetPointer)
}

func TestLoadConfigRejectsUnwrapWithToProtoOnly(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/feature/user
    go_import: example.com/svc/internal/feature/user
    go_type: CreateParams
    proto_import: example.com/svc/gen/grpc/user/v1
    proto_type: CreateUserRequest
    unwrap: User
    direction: to_proto
    package: user
    out: internal/feature/user/mapper_generated.go
`), 0o600))

	_, err := loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unwrap is only valid")
}

func TestLoadConfigRejectsMissingFields(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    # go_type missing
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: mapper.go
`), 0o600))

	_, err := loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "go_type is required")
}

func TestLoadConfigConverterRequiresMatchingDirection(t *testing.T) {
	dir := t.TempDir()
	// from_proto-only direction: converter needs only from_proto.
	configPath := filepath.Join(dir, "protomapgen.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    go_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    direction: from_proto
    package: user
    out: mapper.go
    converters:
      Status:
        from_proto: statusFromProto
`), 0o600))

	_, err := loadConfig(configPath)
	require.NoError(t, err, "from_proto-only converter should be accepted when direction is from_proto")

	// direction=both: half-converter rejected.
	require.NoError(t, os.WriteFile(configPath, []byte(`
targets:
  - go_dir: internal/database
    go_import: example.com/svc/internal/database
    go_type: User
    proto_import: example.com/svc/gen/grpc/user/v1
    package: user
    out: mapper.go
    converters:
      Status:
        to_proto: statusToProto
`), 0o600))

	_, err = loadConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "needs both to_proto and from_proto")
}
