package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"
)

const rootNestedName = "root"

type model struct {
	name      string
	table     string
	alias     string
	columns   map[string]string
	relations []relation
}

type relation struct {
	name  string
	model string
	child bool
}

type stringList []string

func (l *stringList) String() string {
	return strings.Join(*l, ",")
}

func (l *stringList) Set(value string) error {
	if value == "" {
		return fmt.Errorf("value is required")
	}
	*l = append(*l, value)
	return nil
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "fieldmapgen: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	var roots stringList

	fs := flag.NewFlagSet("fieldmapgen", flag.ContinueOnError)
	modelDir := fs.String("model-dir", "internal/database", "directory containing Bun model files")
	outPath := fs.String("out", "gen/database/fieldmap_generated.go", "generated Go output path")
	packageName := fs.String("package", "database", "generated Go package name")
	fs.Var(&roots, "root", "root model type to generate field maps for; repeatable")
	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	if len(roots) == 0 {
		return errors.New("at least one -root is required")
	}

	models, err := parseModelDir(*modelDir)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by fieldmapgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", *packageName)

	for _, rootName := range roots {
		root, ok := models[rootName]
		if !ok {
			return fmt.Errorf("%s model not found", rootName)
		}

		fieldMaps := map[string]fieldMap{}
		visit(models, root, rootNestedName, fieldMaps, map[string]bool{})

		fmt.Fprintf(&buf, "const %sRootNestedName = %q\n\n", root.name, rootNestedName)
		writeMap(&buf, root.name+"RootFields", fieldMaps[rootNestedName].fields)
		writeValidator(&buf, root.name+"Root", root.name+"RootFields")

		nestedNames := make([]string, 0, len(fieldMaps))
		for nestedName := range fieldMaps {
			if nestedName == rootNestedName {
				continue
			}
			nestedNames = append(nestedNames, nestedName)
		}
		sort.Strings(nestedNames)

		for _, nestedName := range nestedNames {
			nestedFieldMap := fieldMaps[nestedName]
			writeMap(&buf, nestedFieldMap.modelName+"Fields", nestedFieldMap.fields)
			writeValidator(&buf, nestedFieldMap.modelName, nestedFieldMap.modelName+"Fields")
		}

		writeMap(&buf, root.name+"Columns", columnsFor(fieldMaps))
		writeValidator(&buf, root.name, root.name+"Columns")
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := writeFileAtomic(*outPath, out); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}

// writeFileAtomic writes data to path by first writing to a temp file in the
// same directory and renaming on success, so a failed write never leaves a
// partial file at path. The output file mode is 0o644.
func writeFileAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".fieldmapgen-*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) //nolint:errcheck // best-effort cleanup; rename removes the file on success

	if _, err := tmp.Write(data); err != nil {
		tmp.Close() //nolint:errcheck // already failing
		return fmt.Errorf("write temp file: %w", err)
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close() //nolint:errcheck // already failing
		return fmt.Errorf("chmod temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename temp file: %w", err)
	}
	return nil
}

type fieldMap struct {
	modelName string
	fields    map[string]string
	alias     string
}

func visit(models map[string]model, m model, nestedName string, fieldMaps map[string]fieldMap, seen map[string]bool) {
	if seen[m.name] {
		return
	}
	seen[m.name] = true

	fieldMaps[nestedName] = fieldMap{
		modelName: m.name,
		fields:    m.columns,
		alias:     queryAlias(m, nestedName),
	}

	for _, rel := range m.relations {
		if !rel.child {
			continue
		}

		relModel, ok := models[rel.model]
		if !ok {
			continue
		}

		childName := snake(rel.name)
		if nestedName != rootNestedName {
			childName = nestedName + "." + childName
		}
		visit(models, relModel, childName, fieldMaps, seen)
	}
}

func parseModelDir(dir string) (map[string]model, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read model directory: %w", err)
	}

	models := make(map[string]model)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		fileModels, err := parseModelFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		maps.Copy(models, fileModels)
	}

	return models, nil
}

func parseModelFile(path string) (map[string]model, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse model file: %w", err)
	}

	models := make(map[string]model)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		for _, spec := range gen.Specs {
			typeSpec := spec.(*ast.TypeSpec)
			strct, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			m, ok := parseModel(typeSpec.Name.Name, strct)
			if ok {
				models[m.name] = m
			}
		}
	}

	return models, nil
}

func parseModel(name string, strct *ast.StructType) (model, bool) {
	m := model{
		name:    name,
		columns: make(map[string]string),
	}

	for _, field := range strct.Fields.List {
		tag := structTag(field)
		bunTag := tag.Get("bun")
		if bunTag == "" {
			continue
		}

		if len(field.Names) == 0 && strings.Contains(bunTag, "table:") {
			m.table = tagOptionValue(bunTag, "table")
			m.alias = tagOptionValue(bunTag, "alias")
			continue
		}

		if len(field.Names) == 0 {
			continue
		}

		fieldName := field.Names[0].Name
		if strings.Contains(bunTag, "rel:") {
			m.relations = append(m.relations, relation{
				name:  fieldName,
				model: modelTypeName(field.Type),
				child: isChildRelation(bunTag),
			})
			continue
		}

		column := strings.Split(bunTag, ",")[0]
		if column == "" {
			continue
		}
		m.columns[snake(fieldName)] = column
	}

	sort.Slice(m.relations, func(i, j int) bool {
		return m.relations[i].name < m.relations[j].name
	})

	return m, m.table != ""
}

func columnsFor(fieldMaps map[string]fieldMap) map[string]string {
	columns := make(map[string]string)
	for nestedName, fieldMap := range fieldMaps {
		for field, column := range fieldMap.fields {
			key := field
			if nestedName != rootNestedName {
				key = nestedName + "." + field
			}
			columns[key] = qualifyColumn(fieldMap.alias, column)
		}
	}
	return columns
}

func qualifyColumn(alias, column string) string {
	if alias == "" {
		return column
	}
	return alias + "." + column
}

func queryAlias(m model, nestedName string) string {
	if nestedName == rootNestedName {
		return m.alias
	}
	return strings.ReplaceAll(nestedName, ".", "__")
}

func structTag(field *ast.Field) reflect.StructTag {
	if field.Tag == nil {
		return ""
	}
	return reflect.StructTag(strings.Trim(field.Tag.Value, "`"))
}

func tagOptionValue(tag, key string) string {
	for opt := range strings.SplitSeq(tag, ",") {
		if value, ok := strings.CutPrefix(opt, key+":"); ok {
			return value
		}
	}
	return ""
}

func isChildRelation(tag string) bool {
	for opt := range strings.SplitSeq(tag, ",") {
		switch opt {
		case "rel:has-many", "rel:has-one":
			return true
		}
	}
	return false
}

func modelTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		return modelTypeName(t.X)
	case *ast.ArrayType:
		return modelTypeName(t.Elt)
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

func writeMap(buf *bytes.Buffer, name string, fields map[string]string) {
	fmt.Fprintf(buf, "var %s = map[string]string{\n", name)
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", key, fields[key])
	}
	buf.WriteString("}\n\n")
}

func writeValidator(buf *bytes.Buffer, name, mapName string) {
	fmt.Fprintf(buf, "func Is%sField(field string) bool {\n", name)
	fmt.Fprintf(buf, "\t_, ok := %s[field]\n", mapName)
	buf.WriteString("\treturn ok\n")
	buf.WriteString("}\n\n")
}

func snake(name string) string {
	var out []rune
	runes := []rune(name)
	for i, r := range runes {
		if i > 0 && shouldSplitWord(runes, i) {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	return string(out)
}

func shouldSplitWord(runes []rune, i int) bool {
	prev := runes[i-1]
	curr := runes[i]

	if unicode.IsLower(prev) && unicode.IsUpper(curr) {
		return true
	}
	if unicode.IsUpper(prev) && unicode.IsUpper(curr) && i+1 < len(runes) && unicode.IsLower(runes[i+1]) {
		return true
	}
	return false
}
